"""
NoteX v1.6 - lang.py
Diller: TR (Türkçe) / EN (English) / AZ (Azərbaycanca) / ZH (中文)
"""

DEFAULT_LANG = "tr"
SUPPORTED    = ("tr", "en", "az", "zh")

STRINGS = {
    # ── Genel ────────────────────────────────────────────────────────────────
    "app_subtitle"        : {"tr":"Güçlü & Hafif Not Defteri","en":"Powerful & Lightweight Notepad","az":"Güclü və Yüngül Qeyd Dəftəri","zh":"强大轻便的记事本"},
    "vault_active"        : {"tr":"● Aktif","en":"● Active","az":"● Aktiv","zh":"● 激活"},
    "vault_passive"       : {"tr":"○ Pasif","en":"○ Inactive","az":"○ Passiv","zh":"○ 未激活"},
    "vault_label"         : {"tr":"Şifreli Klasör","en":"Vault","az":"Şifrəli Qovluq","zh":"加密文件夹"},
    "press_enter"         : {"tr":"  [Enter'a basarak menüye dön]","en":"  [Press Enter to return]","az":"  [Menüyə qayıtmaq üçün Enter basın]","zh":"  [按 Enter 返回菜单]"},
    "goodbye"             : {"tr":"Görüşmek üzere! NoteX v","en":"Goodbye! NoteX v","az":"Görüşənədək! NoteX v","zh":"再见！NoteX v"},
    "cancelled"           : {"tr":"İptal edildi.","en":"Cancelled.","az":"Ləğv edildi.","zh":"已取消。"},
    "empty_content"       : {"tr":"⚠  İçerik boş, not oluşturulmadı.","en":"⚠  Empty content, note not created.","az":"⚠  Məzmun boşdur, qeyd yaradılmadı.","zh":"⚠  内容为空，笔记未创建。"},
    "no_template_manual"  : {"tr":"Şablon seçilmedi, manuel düzenlemeye geçildi.","en":"No template, switching to manual.","az":"Şablon seçilmədi, əl ilə redaktəyə keçildi.","zh":"未选模板，切换到手动编辑。"},
    "content_ready"       : {"tr":"Şablon hazırlandı, kaydediliyor...","en":"Template ready, saving...","az":"Şablon hazırlandı, saxlanılır...","zh":"模板已准备好，正在保存..."},
    "manual_hint"         : {"tr":"İçeriği yazın. Bitirmek için [bold]'KAYDET'[/] yazın.","en":"Write content. Type [bold]'SAVE'[/] to finish.","az":"Məzmunu yazın. Bitirmək üçün [bold]'SAXLA'[/] yazın.","zh":"写入内容。输入 [bold]'保存'[/] 完成。"},
    "save_keyword"        : {"tr":"KAYDET","en":"SAVE","az":"SAXLA","zh":"保存"},
    "back"                : {"tr":"↩  Geri","en":"↩  Back","az":"↩  Geri","zh":"↩  返回"},

    # ── Ana Menü ──────────────────────────────────────────────────────────────
    "menu_title"          : {"tr":"Ana Menü","en":"Main Menu","az":"Əsas Menü","zh":"主菜单"},
    "menu_question"       : {"tr":"Ne yapmak istersiniz?","en":"What would you like to do?","az":"Nə etmək istəyirsiniz?","zh":"您想做什么？"},
    "menu_create"         : {"tr":"📝  Yeni not oluştur","en":"📝  Create new note","az":"📝  Yeni qeyd yarat","zh":"📝  创建新笔记"},
    "menu_list"           : {"tr":"📋  Notları listele","en":"📋  List notes","az":"📋  Qeydləri siyahıla","zh":"📋  列出笔记"},
    "menu_delete"         : {"tr":"🗑️   Not sil","en":"🗑️   Delete note","az":"🗑️   Qeydi sil","zh":"🗑️   删除笔记"},
    "menu_find"           : {"tr":"🔍  Not bul","en":"🔍  Find note","az":"🔍  Qeyd tap","zh":"🔍  查找笔记"},
    "menu_edit"           : {"tr":"✏️   Not düzenle","en":"✏️   Edit note","az":"✏️   Qeydi redaktə et","zh":"✏️   编辑笔记"},
    "menu_vault"          : {"tr":"🔐  Şifreli Klasör","en":"🔐  Vault","az":"🔐  Şifrəli Qovluq","zh":"🔐  加密文件夹"},
    "menu_share"          : {"tr":"📡  Not Paylaşma","en":"📡  Note Sharing","az":"📡  Qeyd Paylaşma","zh":"📡  笔记共享"},
    "menu_favorites"      : {"tr":"⭐  Favoriler","en":"⭐  Favorites","az":"⭐  Sevimlilər","zh":"⭐  收藏夹"},
    "menu_settings"       : {"tr":"⚙️   Ayarlar","en":"⚙️   Settings","az":"⚙️   Parametrlər","zh":"⚙️   设置"},
    "menu_quit"           : {"tr":"🚪  Çık","en":"🚪  Quit","az":"🚪  Çıx","zh":"🚪  退出"},

    # ── Not oluştur ───────────────────────────────────────────────────────────
    "create_title"        : {"tr":"📝 Yeni Not Oluştur","en":"📝 Create New Note","az":"📝 Yeni Qeyd Yarat","zh":"📝 创建新笔记"},
    "create_name_q"       : {"tr":"Not adı:","en":"Note name:","az":"Qeyd adı:","zh":"笔记名称："},
    "create_name_empty"   : {"tr":"Not adı boş olamaz.","en":"Note name cannot be empty.","az":"Qeyd adı boş ola bilməz.","zh":"笔记名称不能为空。"},
    "create_template_q"   : {"tr":"Şablon kullanmak ister misiniz?","en":"Use a template?","az":"Şablon istifadə etmək istəyirsiniz?","zh":"是否使用模板？"},
    "create_method_q"     : {"tr":"Not oluşturma yöntemi:","en":"Creation method:","az":"Yaratma üsulu:","zh":"创建方式："},
    "create_method_new"   : {"tr":"✍️   Sıfırdan yaz","en":"✍️   Write from scratch","az":"✍️   Sıfırdan yaz","zh":"✍️   从头写起"},
    "create_method_ext"   : {"tr":"📂  Dışarıdan not dosyası düzenle","en":"📂  Edit external file","az":"📂  Xarici fayl redaktə et","zh":"📂  编辑外部文件"},

    # ── Dışarıdan not ─────────────────────────────────────────────────────────
    "ext_title"           : {"tr":"📂 Dışarıdan Not Dosyası Düzenle","en":"📂 Edit External Note File","az":"📂 Xarici Qeyd Faylını Redaktə Et","zh":"📂 编辑外部笔记文件"},
    "ext_path_q"          : {"tr":"Not dosyasının tam yolunu girin:","en":"Enter full file path:","az":"Tam fayl yolunu daxil edin:","zh":"输入完整文件路径："},
    "ext_path_empty"      : {"tr":"Dosya yolu boş olamaz.","en":"File path cannot be empty.","az":"Fayl yolu boş ola bilməz.","zh":"文件路径不能为空。"},
    "ext_not_found"       : {"tr":"Dosya bulunamadı:","en":"File not found:","az":"Fayl tapılmadı:","zh":"文件未找到："},
    "ext_loaded"          : {"tr":"Dosya yüklendi.","en":"File loaded.","az":"Fayl yükləndi.","zh":"文件已加载。"},
    "ext_edit_hint"       : {"tr":"Yeni içeriği yazın. [bold]'KAYDET'[/] ile bitirin.\n[dim](Boş bırakırsanız değişmez)[/]","en":"Write new content. Type [bold]'SAVE'[/] to finish.\n[dim](Leave empty to keep unchanged)[/]","az":"Yeni məzmunu yazın. [bold]'SAXLA'[/] ilə bitirin.\n[dim](Boş buraxsanız dəyişməz)[/]","zh":"写新内容。输入 [bold]'保存'[/] 完成。\n[dim](留空则不变)[/]"},
    "ext_no_change"       : {"tr":"Değişiklik yapılmadı.","en":"No changes made.","az":"Dəyişiklik edilmədi.","zh":"未做更改。"},
    "ext_saved"           : {"tr":"✓ Dosya güncellendi:","en":"✓ File updated:","az":"✓ Fayl yeniləndi:","zh":"✓ 文件已更新："},
    "ext_save_err"        : {"tr":"✗ Kayıt hatası:","en":"✗ Save error:","az":"✗ Saxlama xətası:","zh":"✗ 保存错误："},
    "ext_save_as_note_q"  : {"tr":"NoteX notlarına da eklemek ister misiniz?","en":"Also add to NoteX notes?","az":"NoteX qeydlərinə də əlavə etmək istəyirsiniz?","zh":"也添加到 NoteX 笔记中？"},
    "ext_note_name_q"     : {"tr":"NoteX'teki not adı:","en":"Note name in NoteX:","az":"NoteX-dəki qeyd adı:","zh":"NoteX 中的笔记名称："},

    # ── Liste ─────────────────────────────────────────────────────────────────
    "list_title"          : {"tr":"📋 Tüm Notlar","en":"📋 All Notes","az":"📋 Bütün Qeydlər","zh":"📋 所有笔记"},
    "list_empty"          : {"tr":"Henüz hiç not yok.","en":"No notes yet.","az":"Hələ heç bir qeyd yoxdur.","zh":"暂无笔记。"},
    "list_col_num"        : {"tr":"#","en":"#","az":"#","zh":"#"},
    "list_col_name"       : {"tr":"Ad","en":"Name","az":"Ad","zh":"名称"},
    "list_col_size"       : {"tr":"Boyut","en":"Size","az":"Ölçü","zh":"大小"},
    "list_col_modified"   : {"tr":"Değiştirilme","en":"Modified","az":"Dəyişdirilmə","zh":"修改时间"},
    "list_view_q"         : {"tr":"Bir notu görüntülemek ister misiniz?","en":"View a note?","az":"Bir qeydi görmək istəyirsiniz?","zh":"是否查看笔记？"},
    "list_which_q"        : {"tr":"Hangi not?","en":"Which note?","az":"Hansı qeyd?","zh":"哪个笔记？"},

    # ── Sil ───────────────────────────────────────────────────────────────────
    "delete_title"        : {"tr":"🗑️  Not Sil","en":"🗑️  Delete Note","az":"🗑️  Qeydi Sil","zh":"🗑️  删除笔记"},
    "delete_none"         : {"tr":"Silinecek not yok.","en":"No notes to delete.","az":"Silinəcək qeyd yoxdur.","zh":"没有可删除的笔记。"},
    "delete_which_q"      : {"tr":"Hangi notu silmek istiyorsunuz?","en":"Which note to delete?","az":"Hansı qeydi silmək istəyirsiniz?","zh":"要删除哪个笔记？"},
    "delete_confirm"      : {"tr":"kalıcı olarak silinecek. Emin misiniz?","en":"will be permanently deleted. Sure?","az":"həmişəlik silinəcək. Əminsiniz?","zh":"将被永久删除。确定吗？"},

    # ── Bul ───────────────────────────────────────────────────────────────────
    "find_title"          : {"tr":"🔍 Not Bul","en":"🔍 Find Note","az":"🔍 Qeyd Tap","zh":"🔍 查找笔记"},
    "find_q"              : {"tr":"Arama terimi:","en":"Search term:","az":"Axtarış termini:","zh":"搜索词："},
    "find_empty_q"        : {"tr":"Arama terimi boş olamaz.","en":"Search term cannot be empty.","az":"Axtarış termini boş ola bilməz.","zh":"搜索词不能为空。"},
    "find_no_result"      : {"tr":"için sonuç bulunamadı.","en":"No results for","az":"üçün nəticə tapılmadı.","zh":"未找到结果："},
    "find_results"        : {"tr":"Sonuçlar","en":"Results","az":"Nəticələr","zh":"结果"},
    "find_view_q"         : {"tr":"Sonuçlardan birini görüntülemek ister misiniz?","en":"View a result?","az":"Nəticələrdən birini görmək istəyirsiniz?","zh":"是否查看某个结果？"},

    # ── Not Düzenleme ─────────────────────────────────────────────────────────
    "edit_title"          : {"tr":"✏️  Not Düzenleme","en":"✏️  Edit Note","az":"✏️  Qeydi Redaktə Et","zh":"✏️  编辑笔记"},
    "edit_none"           : {"tr":"Düzenlenecek not yok.","en":"No notes to edit.","az":"Redaktə ediləcək qeyd yoxdur.","zh":"没有可编辑的笔记。"},
    "edit_which_q"        : {"tr":"Hangi notu düzenlemek istiyorsunuz?","en":"Which note to edit?","az":"Hansı qeydi redaktə etmək istəyirsiniz?","zh":"要编辑哪个笔记？"},
    "edit_action_q"       : {"tr":"Düzenleme modu:","en":"Edit mode:","az":"Redaktə rejimi:","zh":"编辑模式："},
    "edit_append"         : {"tr":"➕  Mevcut içeriğe ekle (önceki korunur)","en":"➕  Append (keep existing)","az":"➕  Mövcud məzmuna əlavə et (əvvəlki saxlanır)","zh":"➕  追加（保留现有内容）"},
    "edit_replace"        : {"tr":"🔄  Tüm içeriği değiştir","en":"🔄  Replace all content","az":"🔄  Bütün məzmunu dəyiş","zh":"🔄  替换全部内容"},
    "edit_rename"         : {"tr":"📝  Adı değiştir","en":"📝  Rename","az":"📝  Adı dəyiş","zh":"📝  重命名"},
    "edit_back"           : {"tr":"↩  Geri","en":"↩  Back","az":"↩  Geri","zh":"↩  返回"},
    "edit_append_hint"    : {"tr":"Eklemek istediğiniz içeriği yazın. [bold]'KAYDET'[/] ile bitirin.","en":"Write content to append. Type [bold]'SAVE'[/] to finish.","az":"Əlavə etmək istədiyiniz məzmunu yazın. [bold]'SAXLA'[/] ilə bitirin.","zh":"写入要追加的内容。输入 [bold]'保存'[/] 完成。"},
    "edit_replace_hint"   : {"tr":"Yeni içeriği yazın. [bold]'KAYDET'[/] ile bitirin.","en":"Write new content. Type [bold]'SAVE'[/] to finish.","az":"Yeni məzmunu yazın. [bold]'SAXLA'[/] ilə bitirin.","zh":"写入新内容。输入 [bold]'保存'[/] 完成。"},
    "edit_empty_warn"     : {"tr":"⚠  Boş içerik, değişiklik yapılmadı.","en":"⚠  Empty content, no changes made.","az":"⚠  Boş məzmun, dəyişiklik edilmədi.","zh":"⚠  内容为空，未做更改。"},
    "edit_new_name_q"     : {"tr":"Yeni ad:","en":"New name:","az":"Yeni ad:","zh":"新名称："},
    "edit_name_empty"     : {"tr":"Ad boş olamaz.","en":"Name cannot be empty.","az":"Ad boş ola bilməz.","zh":"名称不能为空。"},
    "edit_current"        : {"tr":"Mevcut","en":"Current","az":"Mövcud","zh":"当前"},
    "edit_append_label"   : {"tr":"[dim]Ekleme modu — önceki içerik silinmeyecek[/]","en":"[dim]Append mode — existing content preserved[/]","az":"[dim]Əlavə rejimi — əvvəlki məzmun saxlanır[/]","zh":"[dim]追加模式 — 保留现有内容[/]"},

    # ── Şablon ───────────────────────────────────────────────────────────────
    "tmpl_table_title"    : {"tr":"📄 Mevcut Şablonlar","en":"📄 Available Templates","az":"📄 Mövcud Şablonlar","zh":"📄 可用模板"},
    "tmpl_col_id"         : {"tr":"#","en":"#","az":"#","zh":"#"},
    "tmpl_col_name"       : {"tr":"Şablon","en":"Template","az":"Şablon","zh":"模板"},
    "tmpl_col_desc"       : {"tr":"Açıklama","en":"Description","az":"Təsvir","zh":"描述"},
    "tmpl_select_q"       : {"tr":"Hangi şablonu kullanmak istiyorsunuz?","en":"Which template?","az":"Hansı şablonu istifadə etmək istəyirsiniz?","zh":"使用哪个模板？"},
    "tmpl_cancel"         : {"tr":"↩   Vazgeç (manuel yaz)","en":"↩   Cancel (write manually)","az":"↩   Ləğv et (əl ilə yaz)","zh":"↩   取消（手动输入）"},
    "tmpl_not_found"      : {"tr":"Şablon bulunamadı.","en":"Template not found.","az":"Şablon tapılmadı.","zh":"模板未找到。"},
    "tmpl_fill_hint"      : {"tr":"Alanları doldurun. Boş bırakılanlar köşeli parantez gösterilir.","en":"Fill fields. Empty ones shown in brackets.","az":"Sahələri doldurun. Boş olanlar mötərizədə göstərilir.","zh":"填写字段。空字段以括号显示。"},
    "tmpl_date_auto"      : {"tr":"Enter =","en":"Enter =","az":"Enter =","zh":"Enter ="},
    "tmpl_preview"        : {"tr":"👁  Önizleme","en":"👁  Preview","az":"👁  Önizləmə","zh":"👁  预览"},
    "tmpl_action_save"    : {"tr":"✅  Kaydet","en":"✅  Save","az":"✅  Saxla","zh":"✅  保存"},
    "tmpl_action_edit"    : {"tr":"✏️   Düzenle","en":"✏️   Edit","az":"✏️   Redaktə et","zh":"✏️   编辑"},
    "tmpl_action_cancel"  : {"tr":"❌  İptal","en":"❌  Cancel","az":"❌  Ləğv et","zh":"❌  取消"},
    "tmpl_action_q"       : {"tr":"Ne yapmak istersiniz?","en":"What would you like to do?","az":"Nə etmək istəyirsiniz?","zh":"您想做什么？"},
    "tmpl_ref_panel"      : {"tr":"Referans","en":"Reference","az":"İstinad","zh":"参考"},
    "tmpl_edit_hint"      : {"tr":"Yeni içerik yazın. [bold]'KAYDET'[/] ile bitirin.","en":"Write new content. Type [bold]'SAVE'[/] to finish.","az":"Yeni məzmun yazın. [bold]'SAXLA'[/] ilə bitirin.","zh":"写新内容。输入 [bold]'保存'[/] 完成。"},

    # ── Favoriler ─────────────────────────────────────────────────────────────
    "fav_title"           : {"tr":"⭐ Favoriler","en":"⭐ Favorites","az":"⭐ Sevimlilər","zh":"⭐ 收藏夹"},
    "fav_menu_q"          : {"tr":"Favoriler menüsü:","en":"Favorites menu:","az":"Sevimlilər menüsü:","zh":"收藏夹菜单："},
    "fav_add"             : {"tr":"➕  Favorilere dosya ekle","en":"➕  Add to favorites","az":"➕  Sevimlilərə fayl əlavə et","zh":"➕  添加到收藏夹"},
    "fav_remove"          : {"tr":"➖  Dosyayı favorilerinden çıkart","en":"➖  Remove from favorites","az":"➖  Sevimlilərdən faylı çıxart","zh":"➖  从收藏夹移除"},
    "fav_list"            : {"tr":"📋  Favorilerdeki dosyaları listele","en":"📋  List favorites","az":"📋  Sevimlilərdəki faylları siyahıla","zh":"📋  列出收藏"},
    "fav_search"          : {"tr":"🔍  Favorilerimdeki dosyaları ara","en":"🔍  Search favorites","az":"🔍  Sevimlilərimi axtar","zh":"🔍  搜索收藏"},
    "fav_back"            : {"tr":"↩  Geri","en":"↩  Back","az":"↩  Geri","zh":"↩  返回"},
    "fav_empty"           : {"tr":"Favorilerde henüz not yok.","en":"No favorites yet.","az":"Hələ heç bir sevimli yoxdur.","zh":"收藏夹暂无笔记。"},
    "fav_which_add_q"     : {"tr":"Favorilere eklemek istediğiniz notu seçin:","en":"Select note to add to favorites:","az":"Sevimlilərə əlavə etmək istədiyiniz qeydi seçin:","zh":"选择要添加到收藏夹的笔记："},
    "fav_which_remove_q"  : {"tr":"Favorilerden çıkartmak istediğiniz notu seçin:","en":"Select note to remove from favorites:","az":"Sevimlilərdən çıxartmaq istədiyiniz qeydi seçin:","zh":"选择要从收藏夹移除的笔记："},
    "fav_already"         : {"tr":"Bu not zaten favorilerde.","en":"This note is already in favorites.","az":"Bu qeyd artıq sevimlilərdədir.","zh":"此笔记已在收藏夹中。"},
    "fav_not_in_fav"      : {"tr":"Bu not favorilerde değil.","en":"This note is not in favorites.","az":"Bu qeyd sevimlilərdə deyil.","zh":"此笔记不在收藏夹中。"},
    "fav_added"           : {"tr":"✓ Favorilere eklendi:","en":"✓ Added to favorites:","az":"✓ Sevimlilərə əlavə edildi:","zh":"✓ 已添加到收藏夹："},
    "fav_removed"         : {"tr":"✓ Favorilerden çıkartıldı:","en":"✓ Removed from favorites:","az":"✓ Sevimlilərdən çıxarıldı:","zh":"✓ 已从收藏夹移除："},
    "fav_col_name"        : {"tr":"Not Adı","en":"Note Name","az":"Qeyd Adı","zh":"笔记名称"},
    "fav_col_added"       : {"tr":"Eklenme Tarihi","en":"Date Added","az":"Əlavə Tarixi","zh":"添加日期"},
    "fav_search_q"        : {"tr":"Arama terimi:","en":"Search term:","az":"Axtarış termini:","zh":"搜索词："},
    "fav_search_empty"    : {"tr":"Arama terimi boş olamaz.","en":"Search term cannot be empty.","az":"Axtarış termini boş ola bilməz.","zh":"搜索词不能为空。"},
    "fav_search_no_result": {"tr":"Favorilerde eşleşen not bulunamadı.","en":"No matching favorites found.","az":"Sevimlilərdə uyğun qeyd tapılmadı.","zh":"未在收藏夹中找到匹配项。"},
    "fav_view_q"          : {"tr":"Bir notu görüntülemek ister misiniz?","en":"View a note?","az":"Bir qeydi görmək istəyirsiniz?","zh":"是否查看笔记？"},

    # ── Vault ─────────────────────────────────────────────────────────────────
    "vault_title"         : {"tr":"🔐 Şifreli Klasör","en":"🔐 Vault","az":"🔐 Şifrəli Qovluq","zh":"🔐 加密文件夹"},
    "vault_inactive_msg"  : {"tr":"Şifreli klasör aktif değil.\nAyarlar → Şifreli Klasör Hizmeti","en":"Vault inactive.\nSettings → Vault Service","az":"Şifrəli qovluq aktiv deyil.\nParametrlər → Şifrəli Qovluq Xidməti","zh":"加密文件夹未激活。\n设置 → 加密文件夹服务"},
    "vault_login_title"   : {"tr":"🔐 Şifreli Klasör — Giriş","en":"🔐 Vault — Login","az":"🔐 Şifrəli Qovluq — Giriş","zh":"🔐 加密文件夹 — 登录"},
    "vault_login_hint"    : {"tr":"Şifrenizi girin.","en":"Enter your password.","az":"Şifrənizi daxil edin.","zh":"输入您的密码。"},
    "vault_pw_prompt"     : {"tr":"🔑 Şifre:","en":"🔑 Password:","az":"🔑 Şifrə:","zh":"🔑 密码："},
    "vault_access_ok"     : {"tr":"✓ Erişim sağlandı!","en":"✓ Access granted!","az":"✓ Giriş təmin edildi!","zh":"✓ 访问已授权！"},
    "vault_notes_count"   : {"tr":"not","en":"notes","az":"qeyd","zh":"笔记"},
    "vault_menu_list"     : {"tr":"📋  Şifreli notları listele","en":"📋  List vault notes","az":"📋  Şifrəli qeydləri siyahıla","zh":"📋  列出加密笔记"},
    "vault_menu_add"      : {"tr":"📥  Not ekle (Normal → Şifreli)","en":"📥  Add (Normal → Vault)","az":"📥  Əlavə et (Normal → Şifrəli)","zh":"📥  添加（普通→加密）"},
    "vault_menu_remove"   : {"tr":"📤  Notu çıkar (Şifreli → Normal)","en":"📤  Remove (Vault → Normal)","az":"📤  Çıxar (Şifrəli → Normal)","zh":"📤  移出（加密→普通）"},
    "vault_menu_delete"   : {"tr":"🗑️   Şifreli notu sil","en":"🗑️   Delete vault note","az":"🗑️   Şifrəli qeydi sil","zh":"🗑️   删除加密笔记"},
    "vault_menu_back"     : {"tr":"↩   Ana Menüye Dön","en":"↩   Back to Main Menu","az":"↩   Əsas Menüyə Qayıt","zh":"↩   返回主菜单"},
    "vault_list_title"    : {"tr":"🔐 Şifreli Notlar","en":"🔐 Vault Notes","az":"🔐 Şifrəli Qeydlər","zh":"🔐 加密笔记"},
    "vault_list_empty"    : {"tr":"Şifreli klasörde not yok.","en":"No notes in vault.","az":"Şifrəli qovluqda qeyd yoxdur.","zh":"加密文件夹中没有笔记。"},
    "vault_add_title"     : {"tr":"📥 Not Ekle","en":"📥 Add Note","az":"📥 Qeyd Əlavə Et","zh":"📥 添加笔记"},
    "vault_add_none"      : {"tr":"Taşınacak not yok.","en":"No notes to move.","az":"Köçürüləcək qeyd yoxdur.","zh":"没有可移动的笔记。"},
    "vault_add_which_q"   : {"tr":"Hangi notu taşımak istiyorsunuz?","en":"Which note to move?","az":"Hansı qeydi köçürmək istəyirsiniz?","zh":"要移动哪个笔记？"},
    "vault_add_confirm"   : {"tr":"şifreli klasöre taşınacak. Emin misiniz?","en":"will be moved to vault. Sure?","az":"şifrəli qovluğa köçürüləcək. Əminsiniz?","zh":"将移至加密文件夹。确定吗？"},
    "vault_remove_title"  : {"tr":"📤 Notu Çıkar","en":"📤 Remove Note","az":"📤 Qeydi Çıxar","zh":"📤 移出笔记"},
    "vault_remove_none"   : {"tr":"Çıkarılacak not yok.","en":"No notes to remove.","az":"Çıxarılacaq qeyd yoxdur.","zh":"没有可移出的笔记。"},
    "vault_remove_which_q": {"tr":"Hangi notu çıkarmak istiyorsunuz?","en":"Which note to remove?","az":"Hansı qeydi çıxarmaq istəyirsiniz?","zh":"要移出哪个笔记？"},
    "vault_remove_confirm": {"tr":"normal klasöre taşınacak. Emin misiniz?","en":"will be moved. Sure?","az":"normal qovluğa köçürüləcək. Əminsiniz?","zh":"将移至普通文件夹。确定吗？"},
    "vault_delete_title"  : {"tr":"🗑️  Şifreli Notu Sil","en":"🗑️  Delete Vault Note","az":"🗑️  Şifrəli Qeydi Sil","zh":"🗑️  删除加密笔记"},
    "vault_delete_none"   : {"tr":"Silinecek not yok.","en":"No notes to delete.","az":"Silinəcək qeyd yoxdur.","zh":"没有可删除的笔记。"},
    "vault_delete_which_q": {"tr":"Hangi notu silmek istiyorsunuz?","en":"Which note to delete?","az":"Hansı qeydi silmək istəyirsiniz?","zh":"要删除哪个笔记？"},
    "vault_delete_confirm": {"tr":"kalıcı silinecek. Emin misiniz?","en":"will be deleted. Sure?","az":"həmişəlik silinəcək. Əminsiniz?","zh":"将被永久删除。确定吗？"},

    # ── Vault Servis ──────────────────────────────────────────────────────────
    "vsvc_title"          : {"tr":"🔐 Şifreli Klasör Hizmeti","en":"🔐 Vault Service","az":"🔐 Şifrəli Qovluq Xidməti","zh":"🔐 加密文件夹服务"},
    "vsvc_status"         : {"tr":"Durum:","en":"Status:","az":"Vəziyyət:","zh":"状态："},
    "vsvc_active"         : {"tr":"● AKTİF","en":"● ACTIVE","az":"● AKTİV","zh":"● 已激活"},
    "vsvc_passive"        : {"tr":"○ PASİF","en":"○ INACTIVE","az":"○ PASİV","zh":"○ 未激活"},
    "vsvc_action_q"       : {"tr":"İşlem seçin:","en":"Select action:","az":"Əməliyyat seçin:","zh":"选择操作："},
    "vsvc_activate"       : {"tr":"✅  Aktif et","en":"✅  Activate","az":"✅  Aktivləşdir","zh":"✅  激活"},
    "vsvc_change_pw"      : {"tr":"🔑  Şifreyi değiştir","en":"🔑  Change password","az":"🔑  Şifrəni dəyiş","zh":"🔑  更改密码"},
    "vsvc_deactivate"     : {"tr":"❌  Devre dışı bırak","en":"❌  Deactivate","az":"❌  Deaktivləşdir","zh":"❌  停用"},
    "vsvc_back"           : {"tr":"↩   Geri","en":"↩   Back","az":"↩   Geri","zh":"↩   返回"},
    "vsvc_new_pw"         : {"tr":"🔑 Yeni şifre      :","en":"🔑 New password    :","az":"🔑 Yeni şifrə      :","zh":"🔑 新密码          :"},
    "vsvc_repeat_pw"      : {"tr":"🔑 Şifreyi tekrarla:","en":"🔑 Repeat password :","az":"🔑 Şifrəni təkrarla:","zh":"🔑 重复密码         :"},
    "vsvc_pw_mismatch"    : {"tr":"✗ Şifreler eşleşmiyor!","en":"✗ Passwords do not match!","az":"✗ Şifrələr uyğun gəlmir!","zh":"✗ 密码不匹配！"},
    "vsvc_pw_short"       : {"tr":"✗ En az 4 karakter olmalı!","en":"✗ At least 4 characters!","az":"✗ Ən az 4 simvol olmalıdır!","zh":"✗ 至少需要4个字符！"},
    "vsvc_old_pw"         : {"tr":"🔑 Mevcut şifre:","en":"🔑 Current password:","az":"🔑 Cari şifrə:","zh":"🔑 当前密码："},
    "vsvc_deact_warn"     : {"tr":"DİKKAT: Şifreli notlara erişilemez.\nÖnce notları çıkarın.","en":"WARNING: Vault notes inaccessible.\nRemove notes first.","az":"DİQQƏT: Şifrəli qeydlərə daxil olmaq mümkün olmayacaq.\nƏvvəlcə qeydləri çıxarın.","zh":"警告：将无法访问加密笔记。\n请先移出笔记。"},
    "vsvc_deact_confirm"  : {"tr":"Yine de devam?","en":"Continue anyway?","az":"Yenə də davam et?","zh":"仍然继续？"},
    "vsvc_folder_info"    : {"tr":"Şifreli klasör:","en":"Vault folder:","az":"Şifrəli qovluq:","zh":"加密文件夹："},
    "vsvc_config_info"    : {"tr":"Yapılandırma:","en":"Configuration:","az":"Konfiqurasiya:","zh":"配置："},

    # ── Not Paylaşma ──────────────────────────────────────────────────────────
    "share_title"         : {"tr":"📡 Note Sharing Service","en":"📡 Note Sharing Service","az":"📡 Qeyd Paylaşma Xidməti","zh":"📡 笔记共享服务"},
    "share_version"       : {"tr":"v1.0.1 — Not Paylaşma Hizmeti","en":"v1.0.1 — Note Sharing Service","az":"v1.0.1 — Qeyd Paylaşma Xidməti","zh":"v1.0.1 — 笔记共享服务"},
    "share_loading"       : {"tr":"Yükleniyor...","en":"Loading...","az":"Yüklənir...","zh":"加载中..."},
    "share_loading_back"  : {"tr":"NoteX'e dönülüyor...","en":"Returning to NoteX...","az":"NoteX-ə qayıdılır...","zh":"正在返回 NoteX..."},
    "share_inactive_warn" : {"tr":"Not paylaşma servisi kapalı.\nAyarlar → Not Paylaşma Hizmeti","en":"Share service is off.\nSettings → Note Sharing Service","az":"Paylaşma xidməti bağlıdır.\nParametrlər → Qeyd Paylaşma Xidməti","zh":"共享服务已关闭。\n设置 → 笔记共享服务"},
    "share_id_error"      : {"tr":"NoteX ID hatası! Servis başlatılamıyor.","en":"NoteX ID error! Cannot start service.","az":"NoteX ID xətası! Xidmət başladıla bilmir.","zh":"NoteX ID 错误！无法启动服务。"},
    "share_id_tampered"   : {"tr":"⚠  ID DOSYASI DEĞİŞTİRİLMİŞ VEYA SİLİNMİŞ!\nNote sharing service devre dışı bırakıldı.","en":"⚠  ID FILE TAMPERED OR DELETED!\nNote sharing service disabled.","az":"⚠  ID FAYLI DƏYİŞDİRİLMİŞ VƏ YA SİLİNMİŞDİR!\nQeyd paylaşma xidməti deaktivləşdirildi.","zh":"⚠  ID 文件已被篡改或删除！\n笔记共享服务已停用。"},
    "share_menu_send"     : {"tr":">Not gönder","en":">Send note","az":">Qeyd göndər","zh":">发送笔记"},
    "share_menu_history"  : {"tr":">Geçmiş transferler","en":">Transfer history","az":">Transfer tarixi","zh":">传输历史"},
    "share_menu_about"    : {"tr":">Hakkımda","en":">About","az":">Haqqımda","zh":">关于"},
    "share_menu_settings" : {"tr":">Ayarlar","en":">Settings","az":">Parametrlər","zh":">设置"},
    "share_menu_back"     : {"tr":">NoteX'e geri dön","en":">Return to NoteX","az":">NoteX-ə qayıt","zh":">返回 NoteX"},
    "share_send_title"    : {"tr":"📤 Not Gönder","en":"📤 Send Note","az":"📤 Qeyd Göndər","zh":"📤 发送笔记"},
    "share_target_id_q"   : {"tr":"Alıcının NoteX ID'sini girin (örn. 38471XK):","en":"Enter recipient NoteX ID (e.g. 38471XK):","az":"Alıcının NoteX ID-sini daxil edin (məs. 38471XK):","zh":"输入收件人 NoteX ID（例如 38471XK）："},
    "share_target_id_empty": {"tr":"NoteX ID boş olamaz.","en":"NoteX ID cannot be empty.","az":"NoteX ID boş ola bilməz.","zh":"NoteX ID 不能为空。"},
    "share_searching"     : {"tr":"Hedef cihaz aranıyor...","en":"Searching for target device...","az":"Hədəf cihaz axtarılır...","zh":"正在搜索目标设备..."},
    "share_not_found"     : {"tr":"Cihaz bulunamadı. Aynı ağda olduğunuzdan emin olun.","en":"Device not found. Ensure same network.","az":"Cihaz tapılmadı. Eyni şəbəkədə olduğunuzdan əmin olun.","zh":"未找到设备。请确保在同一网络中。"},
    "share_which_note_q"  : {"tr":"Hangi notu göndermek istiyorsunuz?","en":"Which note to send?","az":"Hansı qeydi göndərmək istəyirsiniz?","zh":"要发送哪个笔记？"},
    "share_no_notes"      : {"tr":"Gönderilecek not yok.","en":"No notes to send.","az":"Göndəriləcək qeyd yoxdur.","zh":"没有可发送的笔记。"},
    "share_sending"       : {"tr":"Gönderiliyor...","en":"Sending...","az":"Göndərilir...","zh":"发送中..."},
    "share_offer_title"   : {"tr":"📨 Gelen Not Teklifi","en":"📨 Incoming Note Offer","az":"📨 Gələn Qeyd Təklifi","zh":"📨 收到笔记请求"},
    "share_offer_accept_q": {"tr":"Kabul etmek istiyor musunuz?","en":"Accept?","az":"Qəbul etmək istəyirsiniz?","zh":"是否接受？"},
    "share_history_title" : {"tr":"📋 Transfer Geçmişi","en":"📋 Transfer History","az":"📋 Transfer Tarixi","zh":"📋 传输历史"},
    "share_history_empty" : {"tr":"Henüz transfer yok.","en":"No transfers yet.","az":"Hələ heç bir transfer yoxdur.","zh":"暂无传输记录。"},
    "share_col_dir"       : {"tr":"Yön","en":"Dir","az":"İstiqamət","zh":"方向"},
    "share_col_peer"      : {"tr":"Karşı Taraf","en":"Peer","az":"Qarşı Tərəf","zh":"对方"},
    "share_col_note"      : {"tr":"Not","en":"Note","az":"Qeyd","zh":"笔记"},
    "share_col_status"    : {"tr":"Durum","en":"Status","az":"Vəziyyət","zh":"状态"},
    "share_col_time"      : {"tr":"Zaman","en":"Time","az":"Zaman","zh":"时间"},
    "share_about_title"   : {"tr":"ℹ️  Hakkımda","en":"ℹ️  About","az":"ℹ️  Haqqımda","zh":"ℹ️  关于"},
    "share_settings_title": {"tr":"⚙️  NSS Ayarları","en":"⚙️  NSS Settings","az":"⚙️  NSS Parametrləri","zh":"⚙️  NSS 设置"},
    "share_port"          : {"tr":"Port","en":"Port","az":"Port","zh":"端口"},
    "share_local_ip"      : {"tr":"Yerel IP","en":"Local IP","az":"Yerli IP","zh":"本地 IP"},
    "share_nss_version"   : {"tr":"NSS Versiyon","en":"NSS Version","az":"NSS Versiya","zh":"NSS 版本"},
    "share_notex_ver"     : {"tr":"NoteX Versiyon","en":"NoteX Version","az":"NoteX Versiya","zh":"NoteX 版本"},
    "share_blocked_q"     : {"tr":"Kara listeye almak istediğiniz NoteX ID:","en":"NoteX ID to blacklist:","az":"Qara siyahıya almaq istədiyiniz NoteX ID:","zh":"要列入黑名单的 NoteX ID："},
    "share_unblock_q"     : {"tr":"Kara listeden çıkartmak istediğiniz NoteX ID:","en":"NoteX ID to remove from blacklist:","az":"Qara siyahıdan çıxartmaq istədiyiniz NoteX ID:","zh":"要从黑名单移除的 NoteX ID："},
    "share_blocked_added" : {"tr":"✓ Kara listeye eklendi:","en":"✓ Added to blacklist:","az":"✓ Qara siyahıya əlavə edildi:","zh":"✓ 已添加到黑名单："},
    "share_blocked_removed": {"tr":"✓ Kara listeden çıkartıldı:","en":"✓ Removed from blacklist:","az":"✓ Qara siyahıdan çıxarıldı:","zh":"✓ 已从黑名单移除："},
    "share_blocklist_title": {"tr":"🚫 Kara Liste","en":"🚫 Blacklist","az":"🚫 Qara Siyahı","zh":"🚫 黑名单"},
    "share_blocklist_empty": {"tr":"Kara liste boş.","en":"Blacklist is empty.","az":"Qara siyahı boşdur.","zh":"黑名单为空。"},
    "share_blocklist_id_empty": {"tr":"NoteX ID boş olamaz.","en":"NoteX ID cannot be empty.","az":"NoteX ID boş ola bilməz.","zh":"NoteX ID 不能为空。"},
    "share_blocklist_not_found": {"tr":"Bu ID kara listede bulunamadı.","en":"This ID is not in the blacklist.","az":"Bu ID qara siyahıda tapılmadı.","zh":"此 ID 不在黑名单中。"},
    "share_blocklist_already": {"tr":"Bu ID zaten kara listede.","en":"This ID is already blacklisted.","az":"Bu ID artıq qara siyahıdadır.","zh":"此 ID 已在黑名单中。"},
    "share_settings_menu_title": {"tr":"Not Paylaşma Hizmeti Ayarları","en":"Note Sharing Service Settings","az":"Qeyd Paylaşma Xidməti Parametrləri","zh":"笔记共享服务设置"},
    "share_bl_add_menu"   : {"tr":"🚫  NoteX ID Kara listeye al","en":"🚫  Blacklist NoteX ID","az":"🚫  NoteX ID-ni qara siyahıya al","zh":"🚫  将 NoteX ID 列入黑名单"},
    "share_bl_remove_menu": {"tr":"✅  NoteX ID Kara listeden çıkart","en":"✅  Remove NoteX ID from blacklist","az":"✅  NoteX ID-ni qara siyahıdan çıxart","zh":"✅  从黑名单移除 NoteX ID"},
    "share_bl_list_menu"  : {"tr":"📋  NoteX ID Listele","en":"📋  List blacklisted IDs","az":"📋  NoteX ID-ləri siyahıla","zh":"📋  列出黑名单 ID"},
    "share_bl_col_id"     : {"tr":"NoteX ID","en":"NoteX ID","az":"NoteX ID","zh":"NoteX ID"},
    "share_bl_col_date"   : {"tr":"Engelleme Tarihi","en":"Blocked Date","az":"Bloklanma Tarixi","zh":"屏蔽日期"},
    "share_blocked_by"    : {"tr":"⚠  Kara listedeki ID'den not alım engellendi:","en":"⚠  Blocked incoming note from blacklisted ID:","az":"⚠  Qara siyahıdakı ID-dən qeyd alımı bloklandı:","zh":"⚠  已屏蔽来自黑名单 ID 的笔记："},

    # ── Ayarlar ───────────────────────────────────────────────────────────────
    "settings_title"      : {"tr":"⚙️  Ayarlar","en":"⚙️  Settings","az":"⚙️  Parametrlər","zh":"⚙️  设置"},
    "settings_q"          : {"tr":"Ayarlar menüsü:","en":"Settings menu:","az":"Parametrlər menüsü:","zh":"设置菜单："},
    "settings_info"       : {"tr":"ℹ️   Yazılım Bilgileri","en":"ℹ️   App Info","az":"ℹ️   Proqram Haqqında","zh":"ℹ️   应用信息"},
    "settings_color"      : {"tr":"🎨  Yazı Rengini Değiştir","en":"🎨  Change Text Color","az":"🎨  Mətn Rəngini Dəyiş","zh":"🎨  更改文本颜色"},
    "settings_vault"      : {"tr":"🔐  Şifreli Klasör Hizmeti","en":"🔐  Vault Service","az":"🔐  Şifrəli Qovluq Xidməti","zh":"🔐  加密文件夹服务"},
    "settings_backup"     : {"tr":"💾  Yedekleme Sistemi","en":"💾  Backup System","az":"💾  Ehtiyat Nüsxə Sistemi","zh":"💾  备份系统"},
    "settings_lang"       : {"tr":"🌐  Dil Ayarları","en":"🌐  Language Settings","az":"🌐  Dil Parametrləri","zh":"🌐  语言设置"},
    "settings_customize"  : {"tr":"🖌️   Özelleştir","en":"🖌️   Customize","az":"🖌️   Fərdiləşdir","zh":"🖌️   自定义"},
    "settings_changelog"  : {"tr":"📋  Güncelleme Notları","en":"📋  Changelog","az":"📋  Yenilik Qeydləri","zh":"📋  更新日志"},
    "settings_share_svc"  : {"tr":"📡  Not Paylaşma Hizmeti","en":"📡  Note Sharing Service","az":"📡  Qeyd Paylaşma Xidməti","zh":"📡  笔记共享服务"},
    "settings_reset"      : {"tr":"🔴  Sıfırla","en":"🔴  Reset","az":"🔴  Sıfırla","zh":"🔴  重置"},
    "settings_back"       : {"tr":"↩   Geri","en":"↩   Back","az":"↩   Geri","zh":"↩   返回"},

    # ── Not Paylaşma Servis toggle ────────────────────────────────────────────
    "svc_share_title"      : {"tr":"📡 Not Paylaşma Hizmeti","en":"📡 Note Sharing Service","az":"📡 Qeyd Paylaşma Xidməti","zh":"📡 笔记共享服务"},
    "svc_share_status"     : {"tr":"Durum:","en":"Status:","az":"Vəziyyət:","zh":"状态："},
    "svc_share_active"     : {"tr":"● AKTİF","en":"● ACTIVE","az":"● AKTİV","zh":"● 已激活"},
    "svc_share_passive"    : {"tr":"○ PASİF","en":"○ INACTIVE","az":"○ PASİV","zh":"○ 未激活"},
    "svc_share_enable"     : {"tr":"✅  Hizmeti Aç","en":"✅  Enable Service","az":"✅  Xidməti Aç","zh":"✅  启用服务"},
    "svc_share_disable"    : {"tr":"❌  Hizmeti Kapat","en":"❌  Disable Service","az":"❌  Xidməti Bağla","zh":"❌  禁用服务"},
    "svc_share_back"       : {"tr":"↩   Geri","en":"↩   Back","az":"↩   Geri","zh":"↩   返回"},
    "svc_share_enabled_ok" : {"tr":"✓ Not paylaşma hizmeti açıldı.","en":"✓ Note sharing service enabled.","az":"✓ Qeyd paylaşma xidməti açıldı.","zh":"✓ 笔记共享服务已启用。"},
    "svc_share_disabled_ok": {"tr":"✓ Not paylaşma hizmeti kapatıldı.","en":"✓ Note sharing service disabled.","az":"✓ Qeyd paylaşma xidməti bağlandı.","zh":"✓ 笔记共享服务已禁用。"},

    # ── App Info ──────────────────────────────────────────────────────────────
    "info_title"           : {"tr":"Yazılım Bilgileri","en":"App Info","az":"Proqram Haqqında","zh":"应用信息"},
    "info_appname"         : {"tr":"Yazılım Adı","en":"App Name","az":"Proqram Adı","zh":"应用名称"},
    "info_version"         : {"tr":"Versiyon","en":"Version","az":"Versiya","zh":"版本"},
    "info_notedir"         : {"tr":"Not Klasörü","en":"Notes Folder","az":"Qeydlər Qovluğu","zh":"笔记文件夹"},
    "info_secdir"          : {"tr":"Şifreli Klasör","en":"Vault Folder","az":"Şifrəli Qovluq","zh":"加密文件夹"},
    "info_tmplfile"        : {"tr":"Şablon Dosyası","en":"Template File","az":"Şablon Faylı","zh":"模板文件"},
    "info_color"           : {"tr":"Yazı Rengi","en":"Text Color","az":"Mətn Rəngi","zh":"文本颜色"},
    "info_notecount"       : {"tr":"Not Sayısı","en":"Note Count","az":"Qeyd Sayı","zh":"笔记数量"},
    "info_seccount"        : {"tr":"Şifreli Not Sayısı","en":"Vault Note Count","az":"Şifrəli Qeyd Sayı","zh":"加密笔记数量"},
    "info_vault_status"    : {"tr":"Vault Durumu","en":"Vault Status","az":"Vault Vəziyyəti","zh":"加密文件夹状态"},
    "info_tmplcount"       : {"tr":"Şablon Sayısı","en":"Template Count","az":"Şablon Sayı","zh":"模板数量"},
    "info_backupdir"       : {"tr":"Yedekleme Klasörü","en":"Backup Folder","az":"Ehtiyat Nüsxə Qovluğu","zh":"备份文件夹"},
    "info_lang"            : {"tr":"Dil","en":"Language","az":"Dil","zh":"语言"},
    "info_font_size"       : {"tr":"Yazı Boyutu","en":"Font Size","az":"Yazı Ölçüsü","zh":"字体大小"},
    "info_font_style"      : {"tr":"Yazı Tipi","en":"Font Style","az":"Yazı Stili","zh":"字体样式"},
    "info_bg_color"        : {"tr":"Arka Plan","en":"Background","az":"Arxa Fon","zh":"背景"},
    "info_share_status"    : {"tr":"Paylaşım Servisi","en":"Share Service","az":"Paylaşma Xidməti","zh":"共享服务"},
    "info_notex_id"        : {"tr":"NoteX ID","en":"NoteX ID","az":"NoteX ID","zh":"NoteX ID"},
    "info_vault_active"    : {"tr":"Aktif ✓","en":"Active ✓","az":"Aktiv ✓","zh":"已激活 ✓"},
    "info_vault_passive"   : {"tr":"Pasif","en":"Inactive","az":"Passiv","zh":"未激活"},
    "info_fav_count"       : {"tr":"Favori Sayısı","en":"Favorite Count","az":"Sevimli Sayı","zh":"收藏数量"},

    # ── Renk ──────────────────────────────────────────────────────────────────
    "color_q"              : {"tr":"Yeni yazı rengi seçin:","en":"Select new text color:","az":"Yeni mətn rəngi seçin:","zh":"选择新文本颜色："},
    "color_set"            : {"tr":"✓ Renk ayarlandı:","en":"✓ Color set to:","az":"✓ Rəng ayarlandı:","zh":"✓ 颜色已设置为："},
    "color_as"             : {"tr":"","en":"","az":"","zh":""},

    # ── Özelleştirme ──────────────────────────────────────────────────────────
    "cust_title"           : {"tr":"🖌️  Özelleştirme","en":"🖌️  Customization","az":"🖌️  Fərdiləşdirmə","zh":"🖌️  自定义"},
    "cust_q"               : {"tr":"Özelleştirme menüsü:","en":"Customization menu:","az":"Fərdiləşdirmə menüsü:","zh":"自定义菜单："},
    "cust_font_size"       : {"tr":"🔡  Yazı Boyutu","en":"🔡  Font Size","az":"🔡  Yazı Ölçüsü","zh":"🔡  字体大小"},
    "cust_font_style"      : {"tr":"🅰️   Yazı Tipi","en":"🅰️   Font Style","az":"🅰️   Yazı Stili","zh":"🅰️   字体样式"},
    "cust_bg_color"        : {"tr":"🎨  Arka Plan Rengi","en":"🎨  Background Color","az":"🎨  Arxa Fon Rəngi","zh":"🎨  背景颜色"},
    "cust_back"            : {"tr":"↩   Geri","en":"↩   Back","az":"↩   Geri","zh":"↩   返回"},
    "cust_fs_q"            : {"tr":"Yazı boyutu seçin:","en":"Select font size:","az":"Yazı ölçüsü seçin:","zh":"选择字体大小："},
    "cust_fs_small"        : {"tr":"Küçük","en":"Small","az":"Kiçik","zh":"小"},
    "cust_fs_normal"       : {"tr":"Normal","en":"Normal","az":"Normal","zh":"正常"},
    "cust_fs_large"        : {"tr":"Büyük","en":"Large","az":"Böyük","zh":"大"},
    "cust_fs_set"          : {"tr":"✓ Yazı boyutu:","en":"✓ Font size:","az":"✓ Yazı ölçüsü:","zh":"✓ 字体大小："},
    "cust_fst_q"           : {"tr":"Yazı tipi seçin:","en":"Select font style:","az":"Yazı stili seçin:","zh":"选择字体样式："},
    "cust_fst_normal"      : {"tr":"Normal","en":"Normal","az":"Normal","zh":"正常"},
    "cust_fst_bold"        : {"tr":"Kalın (Bold)","en":"Bold","az":"Qalın (Bold)","zh":"粗体"},
    "cust_fst_italic"      : {"tr":"İtalik","en":"Italic","az":"İtalik","zh":"斜体"},
    "cust_fst_bold_italic" : {"tr":"Kalın İtalik","en":"Bold Italic","az":"Qalın İtalik","zh":"粗斜体"},
    "cust_fst_set"         : {"tr":"✓ Yazı tipi:","en":"✓ Font style:","az":"✓ Yazı stili:","zh":"✓ 字体样式："},
    "cust_bg_q"            : {"tr":"Arka plan rengi seçin:","en":"Select background:","az":"Arxa fon rəngi seçin:","zh":"选择背景颜色："},
    "cust_bg_set"          : {"tr":"✓ Arka plan:","en":"✓ Background:","az":"✓ Arxa fon:","zh":"✓ 背景："},
    "cust_bg_default"      : {"tr":"Varsayılan (Terminal)","en":"Default (Terminal)","az":"Standart (Terminal)","zh":"默认（终端）"},
    "cust_bg_dark"         : {"tr":"Koyu Siyah","en":"Dark Black","az":"Tünd Qara","zh":"深黑色"},
    "cust_bg_navy"         : {"tr":"Lacivert","en":"Navy Blue","az":"Tünd Mavi","zh":"藏青色"},
    "cust_bg_dark_green"   : {"tr":"Koyu Yeşil","en":"Dark Green","az":"Tünd Yaşıl","zh":"深绿色"},
    "cust_bg_dark_red"     : {"tr":"Koyu Kırmızı","en":"Dark Red","az":"Tünd Qırmızı","zh":"深红色"},
    "cust_bg_dark_purple"  : {"tr":"Koyu Mor","en":"Dark Purple","az":"Tünd Bənövşəyi","zh":"深紫色"},

    # ── Yedekleme ─────────────────────────────────────────────────────────────
    "bkp_title"            : {"tr":"💾 Yedekleme Sistemi","en":"💾 Backup System","az":"💾 Ehtiyat Nüsxə Sistemi","zh":"💾 备份系统"},
    "bkp_q"                : {"tr":"Yedekleme menüsü:","en":"Backup menu:","az":"Ehtiyat nüsxə menüsü:","zh":"备份菜单："},
    "bkp_do"               : {"tr":"📦  Notlarımı yedekle","en":"📦  Backup notes","az":"📦  Qeydlərimi ehtiyat nüsxəsini yarat","zh":"📦  备份笔记"},
    "bkp_list"             : {"tr":"📋  Mevcut yedekleri listele","en":"📋  List backups","az":"📋  Mövcud ehtiyat nüsxələri siyahıla","zh":"📋  列出备份"},
    "bkp_restore"          : {"tr":"♻️   Yedeği geri yükle","en":"♻️   Restore backup","az":"♻️   Ehtiyat nüsxəni bərpa et","zh":"♻️   恢复备份"},
    "bkp_back"             : {"tr":"↩   Geri","en":"↩   Back","az":"↩   Geri","zh":"↩   返回"},
    "bkp_in_progress"      : {"tr":"Yedekleniyor...","en":"Backing up...","az":"Ehtiyat nüsxə yaradılır...","zh":"备份中..."},
    "bkp_no_notes"         : {"tr":"Yedeklenecek not yok.","en":"No notes to back up.","az":"Ehtiyat nüsxəsi yaradılacaq qeyd yoxdur.","zh":"没有可备份的笔记。"},
    "bkp_no_backups"       : {"tr":"Yedek yok.","en":"No backups yet.","az":"Hələ heç bir ehtiyat nüsxə yoxdur.","zh":"暂无备份。"},
    "bkp_list_title"       : {"tr":"📋 Mevcut Yedekler","en":"📋 Backups","az":"📋 Mövcud Ehtiyat Nüsxələr","zh":"📋 可用备份"},
    "bkp_col_name"         : {"tr":"Yedek Adı","en":"Backup Name","az":"Ehtiyat Nüsxə Adı","zh":"备份名称"},
    "bkp_col_count"        : {"tr":"Not Sayısı","en":"Note Count","az":"Qeyd Sayı","zh":"笔记数量"},
    "bkp_col_date"         : {"tr":"Tarih","en":"Date","az":"Tarix","zh":"日期"},
    "bkp_restore_which_q"  : {"tr":"Hangi yedeği geri yüklemek istiyorsunuz?","en":"Which backup to restore?","az":"Hansı ehtiyat nüsxəni bərpa etmək istəyirsiniz?","zh":"要恢复哪个备份？"},
    "bkp_restore_confirm"  : {"tr":"geri yüklenecek. Emin misiniz?","en":"will be restored. Sure?","az":"bərpa ediləcək. Əminsiniz?","zh":"将被恢复。确定吗？"},
    "bkp_restoring"        : {"tr":"Geri yükleniyor...","en":"Restoring...","az":"Bərpa edilir...","zh":"恢复中..."},

    # ── Dil ───────────────────────────────────────────────────────────────────
    "lang_title"           : {"tr":"🌐 Dil Ayarları","en":"🌐 Language Settings","az":"🌐 Dil Parametrləri","zh":"🌐 语言设置"},
    "lang_current"         : {"tr":"Mevcut dil:","en":"Current language:","az":"Cari dil:","zh":"当前语言："},
    "lang_q"               : {"tr":"Dil seçin:","en":"Select language:","az":"Dil seçin:","zh":"选择语言："},
    "lang_tr"              : {"tr":"🇹🇷  Türkçe","en":"🇹🇷  Turkish","az":"🇹🇷  Türkcə","zh":"🇹🇷  土耳其语"},
    "lang_en"              : {"tr":"🇬🇧  İngilizce","en":"🇬🇧  English","az":"🇬🇧  İngilis dili","zh":"🇬🇧  英语"},
    "lang_az"              : {"tr":"🇦🇿  Azerbaycanca","en":"🇦🇿  Azerbaijani","az":"🇦🇿  Azərbaycanca","zh":"🇦🇿  阿塞拜疆语"},
    "lang_zh"              : {"tr":"🇨🇳  Çince","en":"🇨🇳  Chinese","az":"🇨🇳  Çin dili","zh":"🇨🇳  中文"},
    "lang_back"            : {"tr":"↩   Geri","en":"↩   Back","az":"↩   Geri","zh":"↩   返回"},
    "lang_set"             : {"tr":"✓ Dil değiştirildi.","en":"✓ Language changed.","az":"✓ Dil dəyişdirildi.","zh":"✓ 语言已更改。"},
    "lang_same"            : {"tr":"Dil zaten seçili.","en":"Language already selected.","az":"Dil artıq seçilib.","zh":"语言已选择。"},

    # ── Güncelleme Notları ────────────────────────────────────────────────────
    "clog_title"           : {"tr":"📋 Güncelleme Notları","en":"📋 Changelog","az":"📋 Yenilik Qeydləri","zh":"📋 更新日志"},
    "clog_latest"          : {"tr":"Son Sürüm","en":"Latest","az":"Son Versiya","zh":"最新版本"},

    # ── Sıfırla ───────────────────────────────────────────────────────────────
    "reset_title"          : {"tr":"🔴 Sıfırla","en":"🔴 Reset","az":"🔴 Sıfırla","zh":"🔴 重置"},
    "reset_warn"           : {"tr":"[bold red]⚠  DİKKAT — GERİ ALINAMAZ[/]\n\nTüm notlar, vault, config, şablon arşivi silinecek.\n[dim]Klasör yapısı korunur.[/]",
                              "en":"[bold red]⚠  WARNING — IRREVERSIBLE[/]\n\nAll notes, vault, config, template archive will be deleted.\n[dim]Folder structure preserved.[/]",
                              "az":"[bold red]⚠  DİQQƏT — GERİ QAYTARILMAZ[/]\n\nBütün qeydlər, vault, konfiq, şablon arxivi silinəcək.\n[dim]Qovluq strukturu saxlanılır.[/]",
                              "zh":"[bold red]⚠  警告 — 不可撤销[/]\n\n所有笔记、加密文件夹、配置、模板归档将被删除。\n[dim]文件夹结构保留。[/]"},
    "reset_confirm1"       : {"tr":"Emin misiniz?","en":"Are you sure?","az":"Əminsiniz?","zh":"确定吗？"},
    "reset_confirm2"       : {"tr":"Son onay — geri alınamaz. Devam?","en":"Final confirm — cannot undo. Continue?","az":"Son təsdiq — geri qaytarılmaz. Davam et?","zh":"最终确认 — 不可撤销。继续？"},
    "reset_in_progress"    : {"tr":"Sıfırlanıyor...","en":"Resetting...","az":"Sıfırlanır...","zh":"重置中..."},
    "reset_cancelled"      : {"tr":"Sıfırlama iptal edildi.","en":"Reset cancelled.","az":"Sıfırlama ləğv edildi.","zh":"重置已取消。"},
    "reset_ok_msg"         : {"tr":"Varsayılan ayarlarla devam edecek.","en":"Continuing with default settings.","az":"Standart parametrlərlə davam edəcək.","zh":"将继续使用默认设置。"},
}

def t(key: str, lang: str) -> str:
    """Verilen key için dile göre metni döndür. Bulunamazsa TR'ye, o da yoksa key'e düşer."""
    entry = STRINGS.get(key)
    if entry is None:
        return key
    return entry.get(lang) or entry.get("tr") or key

def get_lang(cfg: dict) -> str:
    lang = cfg.get("lang", DEFAULT_LANG)
    return lang if lang in SUPPORTED else DEFAULT_LANG
